name: Linux Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: get-g++11
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt install -y g++-11
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 40
    - name: build
      run: |        
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
        cmake --build build --config Release
